Button:
  Type: AWS::IoT::Thing
  Properties:
    ThingName: iotbutton_${self:custom.vars.ButtonDSN}

ButtonAttachment:
  Type: AWS::IoT::ThingPrincipalAttachment
  Properties:
    Principal: ${self:custom.vars.CertificateARN}
    ThingName:
      Ref: Button


ButtonPolicy:
  Type: AWS::IoT::Policy
  Properties:
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
      - Action: iot:Publish
        Effect: Allow
        Resource:
          Fn::Join:
          - ''
          - - 'arn:aws:iot:'
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - :topic/iotbutton/${self:custom.vars.ButtonDSN}
            
ButtonPolicyAttachment:
  Type: AWS::IoT::PolicyPrincipalAttachment
  Properties:
    PolicyName:
      Ref: ButtonPolicy
    Principal: ${self:custom.vars.CertificateARN}
